travis:
  secure:
    BINSTAR_TOKEN: D4eAmdrOwEL2wGL1HI2e0PwcUNIeDaGpKMjq3UCjaGG5XPJgTlzPD42rDsLs4/39MNGUz5uUvZKmHOhg/jh8Mv2zG0zjJNEyqkm/9vkBFgn1ZWeyhl7PwTb6LKHoOQjFeZccjgW3n+ojWRgDuAJxUsHwkACF9iBFhkEFgAVVkcQcWWLFKhShnxDQ/cgjo4+bgNOwpNJdXDcnr7MnxFt0YrsaNrJFb4rqGwE6UgyN4L5u8dqGqZrpMpyaHeTfPnARi6ywYWyYqFE2E4ONWtopDBubNZKwhRo3p3ygnT7A0A6BS0NCMgruCuah9XaHGKgEbXLBtdV+2sbgtL20zgaaYybvhWl0yImdxQ2iUJ4NzD8j7+B+ISJsnVQrRvhGvyDWLTFnAk+YcFUUZ/oPy+kUcX8aN3CAKvqKc3UMs4+MT9hlH3AMcOOX/AbGak/WCUQBIvwAI63OjJJZDP6F10JYhKPwJCGZu1py5NaeDNJct7YrxXZwiygdOYTxzrkV9KmGnWXCJx53iLHexy6twr7BEN09klWrJrEv7fgkh9pVbRgP/TUKnlpFTRRvw5O1uU9ORXJWN2oh1mbCdVi8vnQEsJCcjfvCCYHsCaufOwwgBKB0dyrhqlDNfjmve0vqOkV3qzBwN52wxw0I4ffXS3vdXj9vwnsvVfCHUzdA1fwTchA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
