travis:
  secure:
    BINSTAR_TOKEN: mXXZf6nGSqPmEsG2hqOl//Fzwt5yyXRECAiUmEAKP42w3HpsSZVxsG34hnPftBXOxCvKV3M5QavyUrlOeN5ePIjZsiyAx9s8kBWbrgn0cipTvqj/hvHCHpoST/ko/r8c9J17v3OV//Lbm0DgkLWRRTfVseByopUqMAH917K/UCitRpywIpMwMhIMiRfE8AQVGT82AoVgg7u6kVeziSdpU57+iulJKxke8fcfBKllddb9QyLSKpIuzWQPDNz5c1qMWRffaoIx9k3ymZgTj66tO/LLwc0MsI0048oMCChPca7w2vkKJEDF16AfjnM2iu/Eyh7yNs91G/KhkGXg2Y1fiOVMGv5Lx68DeV8qUkHcyUuJgq0/ykJxXrPgrDUskiEFfx/Z/pwV8ceOLX6nLGYcKwj0oMxv08rtcq5fc2EQ1lX1intMhaB/N0oEefWheI3eAZG0UXSh0cLNPfj/2D/OauvkgDH7Z0yxLJYSyMur3phfXyDbzX1K4x+4Ax3CbnHDIN9kezHN1FCtRVDv9PHFvw0VWaosXvJEOzvbeEdE8ZquDCa+ByZIDMWDrKW4CbBECRROgOhytPOq4m/370Ytf5i11Dtsq2KHYOlHo6/sLc5Nq2O72rSyvaBLQ4FcQqxe0upkRDgMXsDGX2NdFwCcmGb1s86u2DUuWSkl5S13pmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
