travis:
  secure:
    BINSTAR_TOKEN: NKIxkLWIzFkS3bUGYcrpULx7/n0c7Q/HNV0JreHx7lAG3ctYyahOMf1RnFKZ8lXCW+YG6vxmRBAXfXJW7LDCPn9ZQ22fC5yq710w1gtNDa18P2bYa7ZYWjDZ0CE2p71z029ubfZ6CoASEQdPDWXvIbX4r9Q4YgORuVgUXmxSIM5WYpruYexPSbmuMAOt67kvMWmyhTm0pOeBx/4IpKj9H6x/eqbbS8Mxgd8AwKtjIsnQC9kWAFr2JctGO80OksXSLyFLRSXd2/ctghe0HTdYBv6m4s1QwedFc1W9Wpq4JJnFBSoNRSUAhH76jJQG8BHHxLebzE8fVT4sr2THpetqfQN4TT57IrvQeLG7x6PqwAQ3CzgJRgA9V3gbAm6dJDn//RGOqoBcwjlbUWN/m5gYT/yzyQd4Kv0OvDi85D6qJ5Bz3xCkMXj0TJq1QgmL/XUmD+ei2rqaDGTWCZkQTiyttBMV2OOO4eciDa9f52rx921sNIhiElEuYImSixshS+a0OUkMvGSnvWc7XA6vN/VyNtdcnyuEAriSLnTGLxDugeyVadntY7UfEs4LBmxz6QFfS5FAqc/4gMM2mDnWdKhZfguP7ZFqh1aZsicegC4R/0mPDAN63T75eURYFcwib1cPT4MDoIBCYDWq9d1L6gLWEKazzXQi656h7Us8i/irIQU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
