appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZTI1SaNODXzimQzt5bjZXRodkcA9n7eQEjxepsCXaaoQwau7Z36+XS+5mfjzVy4HyQwBMMotx+PFBYZieK+4MX75klPgn4nB/c3wUZu1c4gGiEvpoVlYBZpuq7IGlo0BKPRSsXckMGwq339M5Osx+rgMzWlDn82qdHwqiidMQp0AY6atpc/mxNMD2JMXhWH8MFbZR3Fsf+MLHCKHwW4IYJpnmpT9XpcmOJjKPHJu9SJRjSK3EaJAHZ1wSrykc3rJ/ZlAncCQMZlY5E+u1SzKMGJjCe0SJB7CyPCmR9nMNA64r9LGBDToxWisGSpv3N1TWEUw2CxNnO5ucgCl1lESjNJJWLAWTwosVrqGAzBTcrdB9uyRcr0kU/hiqDsQNIRvFizHLgaWp10qJX46ola2nBQW2E04LXAXTGfc35iKutAudLrI6vJzLrp+Q+pnWYxUweVkhLjmQDwi+4Qxtm+8U0zFUEpzWwpM3V/fVpZ+XUkNgRniATpHKgdXIqFhhA6iOb5CxpgbPkxOR3gilGL0C0pm+iL2nLOKelfdx+QjVTw2pSmzvO60bU7nI3SuqFOEo9YAYG9gUTJL3OnnBYD01aFVhAxeGugmQjIDhkjUwzwejw4k6EddmkmbnrNTf75zBa+Xau3boA5O+jIe2XUJMSU+yIWYsTHBqe81+RswdSY=}
bot:
  automerge: true
